# Generated by Django 5.1 on 2024-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketingaccept',
            field=models.BooleanField(default=False),
        ),
    ]
